security:

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: EmpaathyPress\Bundle\BookStoreBundle\Entity\User, property: username }
                
    encoders:
        EmpaathyPress\Bundle\BookStoreBundle\Entity\User: sha512
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/category/data, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
    firewalls:
        secured_area:
            pattern: .*
            anonymous: ~
            form_login: ~
            logout: ~